# Site settings
title: Steve Mitchell
email: stevecmitchell@gmail.com
description: > # Permission to Play
 Permission to Play is a journey into making tech learning fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
single_footer: '<p>Let us hear what you think. Permission to Play &copy; 2020 <a href="/">latest posts</a></p>'
footer_links:
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: my_disqus_shortname

# Build settings
# markdown: kramdown
