title: Steve Mitchell
logo: "/images/logo.png?raw=true"
description: >
  Full stack developer
  <br><br>
  Cloud-native, microservice architect
  <br><br>
  Perpetual student of technology
  <br><br>
  <a href="https://www.linkedin.com/in/stevencmitchell/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
