# Site settings
title: Cloud Native Topics
email: stevecmitchell@gmail.com
description:
 Cloud-native Topics is a journey into making tech learning fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://smitchell.github.io" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-user']
single_footer: Exploring Cloud-native topics the fun way
footer_links:
  About: ['About', '/about/']
  Writer: ['Steve Mitchell', '/author/steve']
plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-gist

# https://github.com/jekyll/jekyll-gist

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: cloud-native-topics
  disqus_show_comment_count: true

# Google Analytics
google_analytics: UA-1918559-7

# Build settings
markdown: kramdown
kramdown:
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  span:
   line_numbers: true
  block:
   line_numbers: true
