# Site settings
title: Cloud Native Topics
email: stevecmitchell@gmail.com
description:
 Cloud-native Topics is a journey into making tech learning fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-user']
single_footer: Exploring Cloud-native topics the fun way
footer_links:
  About: ['About', '/about/']
  Writer: ['Writer 2015', '/about/']
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: cloud-native-topics

# Google Analytics
google_analytics: UA-1918559-7

# Build settings
# markdown: kramdown
